fix quoting

diff --git a/egachine/tests/common b/egachine/tests/common
--- a/egachine/tests/common
+++ b/egachine/tests/common
@@ -1,9 +1,9 @@
 function runtest () {
     script="$1"
-    echo $script|../src/ejs
+    echo "$script"|../src/ejs
 
     if which valgrind >/dev/null; then
-	error=$(echo $script|valgrind -q --leak-check=yes --log-fd=1 ../src/ejs|grep -i 'lost\|error'||true)
+	error=$(echo "$script"|valgrind -q --leak-check=yes --log-fd=1 ../src/ejs|grep -i 'lost\|error'||true)
 	if [ "x$error" != "x" ]; then
 	    echo Memory leak: "$error"
 	    exit 1
