fix EJS_CFLAGS usage

diff --git a/egachine/configure b/egachine/configure
--- a/egachine/configure
+++ b/egachine/configure
@@ -19436,9 +19436,9 @@ case "$host" in
 	*)
 		{ echo "$as_me:$LINENO: WARNING: Unknown host type: $host assuming unix for spidermonkey" >&5
 echo "$as_me: WARNING: Unknown host type: $host assuming unix for spidermonkey" >&2;}
+		CPPFLAGS="$CPPFLAGS -DXP_UNIX"
 		;;
 esac
-CPPFLAGS="$CPPFLAGS -DJS_THREADSAFE"
 
 
 if test "${ac_cv_header_jsapi_h+set}" = set; then
@@ -19591,13 +19591,16 @@ fi
 
 
 
-echo "$as_me:$LINENO: checking for library containing JS_InitStandardClasses" >&5
-echo $ECHO_N "checking for library containing JS_InitStandardClasses... $ECHO_C" >&6
-if test "${ac_cv_search_JS_InitStandardClasses+set}" = set; then
+EJS_CFLAGS="-I\$(top_srcdir)/src/modules"
+
+
+echo "$as_me:$LINENO: checking for JS_InitStandardClasses in -ljs" >&5
+echo $ECHO_N "checking for JS_InitStandardClasses in -ljs... $ECHO_C" >&6
+if test "${ac_cv_lib_js_JS_InitStandardClasses+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
-  ac_func_search_save_LIBS=$LIBS
-ac_cv_search_JS_InitStandardClasses=no
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-ljs  $LIBS"
 cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
@@ -19641,18 +19644,31 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
-  ac_cv_search_JS_InitStandardClasses="none required"
+  ac_cv_lib_js_JS_InitStandardClasses=yes
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
+ac_cv_lib_js_JS_InitStandardClasses=no
 fi
 rm -f conftest.err conftest.$ac_objext \
       conftest$ac_exeext conftest.$ac_ext
-if test "$ac_cv_search_JS_InitStandardClasses" = no; then
-  for ac_lib in js smjs mozjs; do
-    LIBS="-l$ac_lib  $ac_func_search_save_LIBS"
-    cat >conftest.$ac_ext <<_ACEOF
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_js_JS_InitStandardClasses" >&5
+echo "${ECHO_T}$ac_cv_lib_js_JS_InitStandardClasses" >&6
+if test $ac_cv_lib_js_JS_InitStandardClasses = yes; then
+  SMJS="js"
+else
+
+	echo "$as_me:$LINENO: checking for JS_InitStandardClasses in -lsmjs" >&5
+echo $ECHO_N "checking for JS_InitStandardClasses in -lsmjs... $ECHO_C" >&6
+if test "${ac_cv_lib_smjs_JS_InitStandardClasses+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lsmjs  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
 cat confdefs.h >>conftest.$ac_ext
@@ -19695,36 +19711,173 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
-  ac_cv_search_JS_InitStandardClasses="-l$ac_lib"
-break
+  ac_cv_lib_smjs_JS_InitStandardClasses=yes
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
+ac_cv_lib_smjs_JS_InitStandardClasses=no
 fi
 rm -f conftest.err conftest.$ac_objext \
       conftest$ac_exeext conftest.$ac_ext
-  done
+LIBS=$ac_check_lib_save_LIBS
 fi
-LIBS=$ac_func_search_save_LIBS
-fi
-echo "$as_me:$LINENO: result: $ac_cv_search_JS_InitStandardClasses" >&5
-echo "${ECHO_T}$ac_cv_search_JS_InitStandardClasses" >&6
-if test "$ac_cv_search_JS_InitStandardClasses" != no; then
-  test "$ac_cv_search_JS_InitStandardClasses" = "none required" || LIBS="$ac_cv_search_JS_InitStandardClasses $LIBS"
-
+echo "$as_me:$LINENO: result: $ac_cv_lib_smjs_JS_InitStandardClasses" >&5
+echo "${ECHO_T}$ac_cv_lib_smjs_JS_InitStandardClasses" >&6
+if test $ac_cv_lib_smjs_JS_InitStandardClasses = yes; then
+  SMJS="smjs"
 else
 
-	{ { echo "$as_me:$LINENO: error: Could not find required spidermonkey Javascript library" >&5
-echo "$as_me: error: Could not find required spidermonkey Javascript library" >&2;}
+		echo "$as_me:$LINENO: checking for JS_InitStandardClasses in -lmozjs" >&5
+echo $ECHO_N "checking for JS_InitStandardClasses in -lmozjs... $ECHO_C" >&6
+if test "${ac_cv_lib_mozjs_JS_InitStandardClasses+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lmozjs  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char JS_InitStandardClasses ();
+int
+main ()
+{
+JS_InitStandardClasses ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_mozjs_JS_InitStandardClasses=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_mozjs_JS_InitStandardClasses=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_mozjs_JS_InitStandardClasses" >&5
+echo "${ECHO_T}$ac_cv_lib_mozjs_JS_InitStandardClasses" >&6
+if test $ac_cv_lib_mozjs_JS_InitStandardClasses = yes; then
+  SMJS="mozjs"
+else
+
+			{ { echo "$as_me:$LINENO: error: Could not find required SpiderMonkey library" >&5
+echo "$as_me: error: Could not find required SpiderMonkey library" >&2;}
    { (exit 1); exit 1; }; }
 
 fi
 
 
+fi
 
-EJS_CFLAGS="-I\$(top_srcdir)/src/modules"
 
+fi
+
+
+as_ac_Lib=`echo "ac_cv_lib_$SMJS''_JS_BeginRequest" | $as_tr_sh`
+echo "$as_me:$LINENO: checking for JS_BeginRequest in -l$SMJS" >&5
+echo $ECHO_N "checking for JS_BeginRequest in -l$SMJS... $ECHO_C" >&6
+if eval "test \"\${$as_ac_Lib+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-l$SMJS  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char JS_BeginRequest ();
+int
+main ()
+{
+JS_BeginRequest ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  eval "$as_ac_Lib=yes"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+eval "$as_ac_Lib=no"
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_Lib'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_Lib'}'`" >&6
+if test `eval echo '${'$as_ac_Lib'}'` = yes; then
+  EJS_CFLAGS="$EJS_CFLAGS -DJS_THREADSAFE"
+fi
+
+
+LIBS="-l$SMJS $LIBS"
 
 
 # Check whether --enable-zlib or --disable-zlib was given.
