added io module

diff --git a/egachine/configure b/egachine/configure
--- a/egachine/configure
+++ b/egachine/configure
@@ -466,7 +466,7 @@ ac_includes_default="\
 #endif"
 
 ac_subdirs_all="$ac_subdirs_all libltdl"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CC CFLAGS ac_ct_CC CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE LTDLINCL LIBLTDL EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB DLLTOOL ac_ct_DLLTOOL AS ac_ct_AS OBJDUMP ac_ct_OBJDUMP CPP CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL subdirs EJS_CFLAGS ZLIB_LIBS BUILD_ZLIB_TRUE BUILD_ZLIB_FALSE BUILD_STREAM_TRUE BUILD_STREAM_FALSE BUILD_FILE_TRUE BUILD_FILE_FALSE SIGC_CONFIG SIGC_CFLAGS SIGC_LIBS SIGC_MACROS SOCKET_LIBS BUILD_NET_TRUE BUILD_NET_FALSE TIMER_LIBS BUILD_TIMER_TRUE BUILD_TIMER_FALSE GL_LIBS BUILD_GL_TRUE BUILD_GL_FALSE SDL_CONFIG SDL_CFLAGS SDL_LIBS BUILD_VIDEO_TRUE BUILD_VIDEO_FALSE BUILD_IMAGE_TRUE BUILD_IMAGE_FALSE BUILD_INPUT_TRUE BUILD_INPUT_FALSE SDLMIXER_LIBS BUILD_AUDIO_TRUE BUILD_AUDIO_FALSE PKG_CONFIG ac_pt_PKG_CONFIG SVGL_CFLAGS SVGL_LIBS BUILD_SVGL_TRUE BUILD_SVGL_FALSE TCC_LIBS BUILD_TCC_TRUE BUILD_TCC_FALSE BUILD_LTDL_TRUE BUILD_LTDL_FALSE BUILD_POSIX_TRUE BUILD_POSIX_FALSE MODULE_LDFLAGS LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CC CFLAGS ac_ct_CC CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE LTDLINCL LIBLTDL EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB DLLTOOL ac_ct_DLLTOOL AS ac_ct_AS OBJDUMP ac_ct_OBJDUMP CPP CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL subdirs EJS_CFLAGS ZLIB_LIBS BUILD_ZLIB_TRUE BUILD_ZLIB_FALSE BUILD_STREAM_TRUE BUILD_STREAM_FALSE BUILD_FILE_TRUE BUILD_FILE_FALSE SIGC_CONFIG SIGC_CFLAGS SIGC_LIBS SIGC_MACROS SOCKET_LIBS BUILD_NET_TRUE BUILD_NET_FALSE TIMER_LIBS BUILD_TIMER_TRUE BUILD_TIMER_FALSE GL_LIBS BUILD_GL_TRUE BUILD_GL_FALSE SDL_CONFIG SDL_CFLAGS SDL_LIBS BUILD_VIDEO_TRUE BUILD_VIDEO_FALSE BUILD_IMAGE_TRUE BUILD_IMAGE_FALSE BUILD_INPUT_TRUE BUILD_INPUT_FALSE SDLMIXER_LIBS BUILD_AUDIO_TRUE BUILD_AUDIO_FALSE PKG_CONFIG ac_pt_PKG_CONFIG SVGL_CFLAGS SVGL_LIBS BUILD_SVGL_TRUE BUILD_SVGL_FALSE TCC_LIBS BUILD_TCC_TRUE BUILD_TCC_FALSE BUILD_LTDL_TRUE BUILD_LTDL_FALSE BUILD_POSIX_TRUE BUILD_POSIX_FALSE BUILD_IO_TRUE BUILD_IO_FALSE MODULE_LDFLAGS LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1067,6 +1067,7 @@ Optional Features:
   --enable-tcc            Build tcc module [default=no]
   --enable-ltdl           Build ltdl module [default=no]
   --enable-posix          Build posix module [default=no]
+  --enable-io             Build posix module [default=no]
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -4281,7 +4282,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4284 "configure"' > conftest.$ac_ext
+  echo '#line 4285 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -5627,7 +5628,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:5630:" \
+echo "$as_me:5631:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -6659,11 +6660,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6662: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6663: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6666: \$? = $ac_status" >&5
+   echo "$as_me:6667: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -6892,11 +6893,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6895: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6896: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6899: \$? = $ac_status" >&5
+   echo "$as_me:6900: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -6952,11 +6953,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6955: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6956: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:6959: \$? = $ac_status" >&5
+   echo "$as_me:6960: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -9140,7 +9141,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9143 "configure"
+#line 9144 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -9238,7 +9239,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9241 "configure"
+#line 9242 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11415,11 +11416,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11418: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11419: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:11422: \$? = $ac_status" >&5
+   echo "$as_me:11423: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -11475,11 +11476,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11478: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11479: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:11482: \$? = $ac_status" >&5
+   echo "$as_me:11483: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -12844,7 +12845,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12847 "configure"
+#line 12848 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12942,7 +12943,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12945 "configure"
+#line 12946 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13769,11 +13770,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13772: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13773: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:13776: \$? = $ac_status" >&5
+   echo "$as_me:13777: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -13829,11 +13830,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13832: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13833: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13836: \$? = $ac_status" >&5
+   echo "$as_me:13837: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -15874,11 +15875,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15877: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15878: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15881: \$? = $ac_status" >&5
+   echo "$as_me:15882: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -16107,11 +16108,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16110: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16111: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16114: \$? = $ac_status" >&5
+   echo "$as_me:16115: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -16167,11 +16168,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16170: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16171: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:16174: \$? = $ac_status" >&5
+   echo "$as_me:16175: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -18355,7 +18356,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 18358 "configure"
+#line 18359 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -18453,7 +18454,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 18456 "configure"
+#line 18457 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -22131,11 +22132,29 @@ else
 fi
 
 
+# Check whether --enable-io or --disable-io was given.
+if test "${enable_io+set}" = set; then
+  enableval="$enable_io"
+
+else
+  enable_io=no
+fi;
+
+
+if test x$enable_io = xyes; then
+  BUILD_IO_TRUE=
+  BUILD_IO_FALSE='#'
+else
+  BUILD_IO_TRUE='#'
+  BUILD_IO_FALSE=
+fi
+
+
 LDFLAGS="$LDFLAGS -thread-safe -pthread"
 MODULE_LDFLAGS="-avoid-version -no-undefined -export-symbols \$(srcdir)/export.sym"
 
 
-                                                                                                                                                                                                                                                                                                  ac_config_files="$ac_config_files Makefile tests/Makefile debian/Makefile src/Makefile src/etc/Makefile src/examples/Makefile src/modules/Makefile src/modules/example/Makefile src/modules/zlib/Makefile src/modules/monitorable/Makefile src/modules/stream/Makefile src/modules/file/Makefile src/modules/network/Makefile src/modules/bytearray/Makefile src/modules/egachine/Makefile src/modules/timer/Makefile src/modules/gl/Makefile src/modules/video/Makefile src/modules/video/boost/Makefile src/modules/image/Makefile src/modules/input/Makefile src/modules/audio/Makefile src/modules/svgl/Makefile src/modules/util/Makefile src/modules/jsolait/Makefile src/modules/jsmisc/Makefile src/modules/tcc/Makefile src/modules/ltdl/Makefile src/modules/posix/Makefile"
+                                                                                                                                                                                                                                                                                                            ac_config_files="$ac_config_files Makefile tests/Makefile debian/Makefile src/Makefile src/etc/Makefile src/examples/Makefile src/modules/Makefile src/modules/example/Makefile src/modules/zlib/Makefile src/modules/monitorable/Makefile src/modules/stream/Makefile src/modules/file/Makefile src/modules/network/Makefile src/modules/bytearray/Makefile src/modules/egachine/Makefile src/modules/timer/Makefile src/modules/gl/Makefile src/modules/video/Makefile src/modules/video/boost/Makefile src/modules/image/Makefile src/modules/input/Makefile src/modules/audio/Makefile src/modules/svgl/Makefile src/modules/util/Makefile src/modules/jsolait/Makefile src/modules/jsmisc/Makefile src/modules/tcc/Makefile src/modules/ltdl/Makefile src/modules/posix/Makefile src/modules/io/Makefile"
 
 
 cat >confcache <<\_ACEOF
@@ -22376,6 +22395,13 @@ if test -z "${BUILD_POSIX_TRUE}" && test -z "${BUILD_POSIX_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"BUILD_POSIX\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"BUILD_POSIX\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${BUILD_IO_TRUE}" && test -z "${BUILD_IO_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"BUILD_IO\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"BUILD_IO\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -22847,6 +22873,7 @@ do
   "src/modules/tcc/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/modules/tcc/Makefile" ;;
   "src/modules/ltdl/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/modules/ltdl/Makefile" ;;
   "src/modules/posix/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/modules/posix/Makefile" ;;
+  "src/modules/io/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/modules/io/Makefile" ;;
   "depfiles" ) CONFIG_COMMANDS="$CONFIG_COMMANDS depfiles" ;;
   *) { { echo "$as_me:$LINENO: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
@@ -23056,6 +23083,8 @@ s,@BUILD_LTDL_TRUE@,$BUILD_LTDL_TRUE,;t t
 s,@BUILD_LTDL_FALSE@,$BUILD_LTDL_FALSE,;t t
 s,@BUILD_POSIX_TRUE@,$BUILD_POSIX_TRUE,;t t
 s,@BUILD_POSIX_FALSE@,$BUILD_POSIX_FALSE,;t t
+s,@BUILD_IO_TRUE@,$BUILD_IO_TRUE,;t t
+s,@BUILD_IO_FALSE@,$BUILD_IO_FALSE,;t t
 s,@MODULE_LDFLAGS@,$MODULE_LDFLAGS,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
