cross compilation fixes

diff --git a/egachine/configure b/egachine/configure
--- a/egachine/configure
+++ b/egachine/configure
@@ -466,7 +466,7 @@ ac_includes_default="\
 #endif"
 
 ac_subdirs_all="$ac_subdirs_all libltdl"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CC CFLAGS ac_ct_CC CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE LTDLINCL LIBLTDL build build_cpu build_vendor build_os host host_cpu host_vendor host_os EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB DLLTOOL ac_ct_DLLTOOL AS ac_ct_AS OBJDUMP ac_ct_OBJDUMP CPP CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL subdirs EJS_CFLAGS ZLIB_LIBS BUILD_ZLIB_TRUE BUILD_ZLIB_FALSE BUILD_STREAM_TRUE BUILD_STREAM_FALSE BUILD_FILE_TRUE BUILD_FILE_FALSE SIGC_CONFIG SIGC_CFLAGS SIGC_LIBS SIGC_MACROS SOCKET_LIBS BUILD_NET_TRUE BUILD_NET_FALSE TIMER_LIBS BUILD_TIMER_TRUE BUILD_TIMER_FALSE GL_LIBS BUILD_GL_TRUE BUILD_GL_FALSE SDL_CONFIG SDL_CFLAGS SDL_LIBS BUILD_VIDEO_TRUE BUILD_VIDEO_FALSE BUILD_INPUT_TRUE BUILD_INPUT_FALSE SDLMIXER_LIBS BUILD_AUDIO_TRUE BUILD_AUDIO_FALSE PKG_CONFIG GLFT_CFLAGS GLFT_LIBS SVGL_CFLAGS SVGL_LIBS BUILD_SVGL_TRUE BUILD_SVGL_FALSE MODULE_LDFLAGS LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CC CFLAGS ac_ct_CC CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE LTDLINCL LIBLTDL build build_cpu build_vendor build_os host host_cpu host_vendor host_os EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB DLLTOOL ac_ct_DLLTOOL AS ac_ct_AS OBJDUMP ac_ct_OBJDUMP CPP CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL subdirs EJS_CFLAGS ZLIB_LIBS BUILD_ZLIB_TRUE BUILD_ZLIB_FALSE BUILD_STREAM_TRUE BUILD_STREAM_FALSE BUILD_FILE_TRUE BUILD_FILE_FALSE SIGC_CONFIG SIGC_CFLAGS SIGC_LIBS SIGC_MACROS SOCKET_LIBS BUILD_NET_TRUE BUILD_NET_FALSE TIMER_LIBS BUILD_TIMER_TRUE BUILD_TIMER_FALSE GL_LIBS BUILD_GL_TRUE BUILD_GL_FALSE SDL_CONFIG SDL_CFLAGS SDL_LIBS BUILD_VIDEO_TRUE BUILD_VIDEO_FALSE BUILD_INPUT_TRUE BUILD_INPUT_FALSE SDLMIXER_LIBS BUILD_AUDIO_TRUE BUILD_AUDIO_FALSE PKG_CONFIG SVGL_CFLAGS SVGL_LIBS BUILD_SVGL_TRUE BUILD_SVGL_FALSE MODULE_LDFLAGS LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -21318,15 +21318,25 @@ else
   enable_audio=yes
 fi;
 if test x$enable_audio = xyes; then
-					TMP="$LDFLAGS"
-				LDFLAGS="$LDFLAGS -lmikmod"
-	echo "$as_me:$LINENO: checking for Mix_LoadWAV_RW in -lSDL_mixer" >&5
-echo $ECHO_N "checking for Mix_LoadWAV_RW in -lSDL_mixer... $ECHO_C" >&6
-if test "${ac_cv_lib_SDL_mixer_Mix_LoadWAV_RW+set}" = set; then
+
+
+	ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+	OLD_LIBS="$LIBS"
+	OLD_CPPFLAGS="$CPPFLAGS"
+	SDLMIXER_LIBS="-lSDL_mixer"
+	CPPFLAGS="$SDL_CFLAGS $CPPFLAGS -DUSE_RWOPS"
+	echo "$as_me:$LINENO: checking for Mix_LoadMUS_RW in -lSDL_mixer" >&5
+echo $ECHO_N "checking for Mix_LoadMUS_RW in -lSDL_mixer... $ECHO_C" >&6
+if test "${ac_cv_lib_SDL_mixer_Mix_LoadMUS_RW+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   ac_check_lib_save_LIBS=$LIBS
-LIBS="-lSDL_mixer $SDL_LIBS $LIBS"
+LIBS="-lSDL_mixer "$SDL_LIBS" $LIBS"
 cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
@@ -21340,11 +21350,11 @@ extern "C"
 #endif
 /* We use char because int might match the return type of a gcc2
    builtin and then its argument prototype would still apply.  */
-char Mix_LoadWAV_RW ();
+char Mix_LoadMUS_RW ();
 int
 main ()
 {
-Mix_LoadWAV_RW ();
+Mix_LoadMUS_RW ();
   ;
   return 0;
 }
@@ -21358,7 +21368,7 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   cat conftest.err >&5
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_cxx_werror_flag"			 || test ! -s conftest.err'
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
   { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
@@ -21370,24 +21380,75 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
-  ac_cv_lib_SDL_mixer_Mix_LoadWAV_RW=yes
+  ac_cv_lib_SDL_mixer_Mix_LoadMUS_RW=yes
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
-ac_cv_lib_SDL_mixer_Mix_LoadWAV_RW=no
+ac_cv_lib_SDL_mixer_Mix_LoadMUS_RW=no
 fi
 rm -f conftest.err conftest.$ac_objext \
       conftest$ac_exeext conftest.$ac_ext
 LIBS=$ac_check_lib_save_LIBS
 fi
-echo "$as_me:$LINENO: result: $ac_cv_lib_SDL_mixer_Mix_LoadWAV_RW" >&5
-echo "${ECHO_T}$ac_cv_lib_SDL_mixer_Mix_LoadWAV_RW" >&6
-if test $ac_cv_lib_SDL_mixer_Mix_LoadWAV_RW = yes; then
-  SDLMIXER_LIBS="-lSDL_mixer -lmikmod"
+echo "$as_me:$LINENO: result: $ac_cv_lib_SDL_mixer_Mix_LoadMUS_RW" >&5
+echo "${ECHO_T}$ac_cv_lib_SDL_mixer_Mix_LoadMUS_RW" >&6
+if test $ac_cv_lib_SDL_mixer_Mix_LoadMUS_RW = yes; then
+  SDLMIXER_LIBS="-lSDL_mixer"
 else
 
-		{ { echo "$as_me:$LINENO: error: Could not find required SDL_mixer library
+
+			SDLMIXER_LIBS="-lSDL_mixer -lmikmod"
+			LIBS="$SDLMIXER_LIBS $SDL_LIBS $OLD_LIBS"
+			cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+#include <SDL_mixer.h>
+
+int
+main ()
+{
+
+SDL_RWops* rw;
+Mix_Music *music = Mix_LoadMUS_RW(rw);
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  echo "$as_me:$LINENO: result: yes - using external mikmod" >&5
+echo "${ECHO_T}yes - using external mikmod" >&6
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+					{ { echo "$as_me:$LINENO: error: Could not find required SDL_mixer library
 Perhaps you have to add some -L/path/to/libz to your LDFLAGS
 or your SDL_mixer library is missing Mix_LoadWAV_RW - you need a version newer than 1.2.5
 or disable the audio module by passing --disable-audio to configure" >&5
@@ -21398,8 +21459,19 @@ or disable the audio module by passing --disable-audio to configure" >&2;}
    { (exit 1); exit 1; }; }
 
 fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
 
-	LDFLAGS="$TMP"
+fi
+
+	CPPFLAGS="$OLD_CPPFLAGS"
+	LIBS="$OLD_LIBS"
+
+	ac_ext=cc
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
 
 fi
 
@@ -21421,104 +21493,6 @@ else
   enable_svgl=no
 fi;
 if test x$enable_svgl = xyes; then
-
-  succeeded=no
-
-  if test -z "$PKG_CONFIG"; then
-    # Extract the first word of "pkg-config", so it can be a program name with args.
-set dummy pkg-config; ac_word=$2
-echo "$as_me:$LINENO: checking for $ac_word" >&5
-echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
-if test "${ac_cv_path_PKG_CONFIG+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  case $PKG_CONFIG in
-  [\\/]* | ?:[\\/]*)
-  ac_cv_path_PKG_CONFIG="$PKG_CONFIG" # Let the user override the test with a path.
-  ;;
-  *)
-  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
-for as_dir in $PATH
-do
-  IFS=$as_save_IFS
-  test -z "$as_dir" && as_dir=.
-  for ac_exec_ext in '' $ac_executable_extensions; do
-  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
-    ac_cv_path_PKG_CONFIG="$as_dir/$ac_word$ac_exec_ext"
-    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
-    break 2
-  fi
-done
-done
-
-  test -z "$ac_cv_path_PKG_CONFIG" && ac_cv_path_PKG_CONFIG="no"
-  ;;
-esac
-fi
-PKG_CONFIG=$ac_cv_path_PKG_CONFIG
-
-if test -n "$PKG_CONFIG"; then
-  echo "$as_me:$LINENO: result: $PKG_CONFIG" >&5
-echo "${ECHO_T}$PKG_CONFIG" >&6
-else
-  echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-fi
-
-  fi
-
-  if test "$PKG_CONFIG" = "no" ; then
-     echo "*** The pkg-config script could not be found. Make sure it is"
-     echo "*** in your path, or set the PKG_CONFIG environment variable"
-     echo "*** to the full path to pkg-config."
-     echo "*** Or see http://www.freedesktop.org/software/pkgconfig to get pkg-config."
-  else
-     PKG_CONFIG_MIN_VERSION=0.9.0
-     if $PKG_CONFIG --atleast-pkgconfig-version $PKG_CONFIG_MIN_VERSION; then
-        echo "$as_me:$LINENO: checking for glft" >&5
-echo $ECHO_N "checking for glft... $ECHO_C" >&6
-
-        if $PKG_CONFIG --exists "glft" ; then
-            echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6
-            succeeded=yes
-
-            echo "$as_me:$LINENO: checking GLFT_CFLAGS" >&5
-echo $ECHO_N "checking GLFT_CFLAGS... $ECHO_C" >&6
-            GLFT_CFLAGS=`$PKG_CONFIG --cflags "glft"`
-            echo "$as_me:$LINENO: result: $GLFT_CFLAGS" >&5
-echo "${ECHO_T}$GLFT_CFLAGS" >&6
-
-            echo "$as_me:$LINENO: checking GLFT_LIBS" >&5
-echo $ECHO_N "checking GLFT_LIBS... $ECHO_C" >&6
-            GLFT_LIBS=`$PKG_CONFIG --libs "glft"`
-            echo "$as_me:$LINENO: result: $GLFT_LIBS" >&5
-echo "${ECHO_T}$GLFT_LIBS" >&6
-        else
-            GLFT_CFLAGS=""
-            GLFT_LIBS=""
-            ## If we have a custom action on failure, don't print errors, but
-            ## do set a variable so people can do so.
-            GLFT_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "glft"`
-            echo $GLFT_PKG_ERRORS
-        fi
-
-
-
-     else
-        echo "*** Your version of pkg-config is too old. You need version $PKG_CONFIG_MIN_VERSION or newer."
-        echo "*** See http://www.freedesktop.org/software/pkgconfig"
-     fi
-  fi
-
-  if test $succeeded = yes; then
-     :
-  else
-     { { echo "$as_me:$LINENO: error: Library requirements (glft) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&5
-echo "$as_me: error: Library requirements (glft) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&2;}
-   { (exit 1); exit 1; }; }
-  fi
-
 
   succeeded=no
 
@@ -22505,8 +22479,6 @@ s,@SDLMIXER_LIBS@,$SDLMIXER_LIBS,;t t
 s,@BUILD_AUDIO_TRUE@,$BUILD_AUDIO_TRUE,;t t
 s,@BUILD_AUDIO_FALSE@,$BUILD_AUDIO_FALSE,;t t
 s,@PKG_CONFIG@,$PKG_CONFIG,;t t
-s,@GLFT_CFLAGS@,$GLFT_CFLAGS,;t t
-s,@GLFT_LIBS@,$GLFT_LIBS,;t t
 s,@SVGL_CFLAGS@,$SVGL_CFLAGS,;t t
 s,@SVGL_LIBS@,$SVGL_LIBS,;t t
 s,@BUILD_SVGL_TRUE@,$BUILD_SVGL_TRUE,;t t
