Added ltdl module.

diff --git a/egachine/configure b/egachine/configure
--- a/egachine/configure
+++ b/egachine/configure
@@ -466,7 +466,7 @@ ac_includes_default="\
 #endif"
 
 ac_subdirs_all="$ac_subdirs_all libltdl"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CC CFLAGS ac_ct_CC CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE LTDLINCL LIBLTDL build build_cpu build_vendor build_os host host_cpu host_vendor host_os EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB DLLTOOL ac_ct_DLLTOOL AS ac_ct_AS OBJDUMP ac_ct_OBJDUMP CPP CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL subdirs EJS_CFLAGS ZLIB_LIBS BUILD_ZLIB_TRUE BUILD_ZLIB_FALSE BUILD_STREAM_TRUE BUILD_STREAM_FALSE BUILD_FILE_TRUE BUILD_FILE_FALSE SIGC_CONFIG SIGC_CFLAGS SIGC_LIBS SIGC_MACROS SOCKET_LIBS BUILD_NET_TRUE BUILD_NET_FALSE TIMER_LIBS BUILD_TIMER_TRUE BUILD_TIMER_FALSE GL_LIBS BUILD_GL_TRUE BUILD_GL_FALSE target target_cpu target_vendor target_os SDL_CONFIG SDL_CFLAGS SDL_LIBS BUILD_VIDEO_TRUE BUILD_VIDEO_FALSE BUILD_INPUT_TRUE BUILD_INPUT_FALSE SDLMIXER_LIBS BUILD_AUDIO_TRUE BUILD_AUDIO_FALSE PKG_CONFIG ac_pt_PKG_CONFIG SVGL_CFLAGS SVGL_LIBS BUILD_SVGL_TRUE BUILD_SVGL_FALSE TCC_LIBS BUILD_TCC_TRUE BUILD_TCC_FALSE MODULE_LDFLAGS LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CC CFLAGS ac_ct_CC CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE LTDLINCL LIBLTDL build build_cpu build_vendor build_os host host_cpu host_vendor host_os EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB DLLTOOL ac_ct_DLLTOOL AS ac_ct_AS OBJDUMP ac_ct_OBJDUMP CPP CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL subdirs EJS_CFLAGS ZLIB_LIBS BUILD_ZLIB_TRUE BUILD_ZLIB_FALSE BUILD_STREAM_TRUE BUILD_STREAM_FALSE BUILD_FILE_TRUE BUILD_FILE_FALSE SIGC_CONFIG SIGC_CFLAGS SIGC_LIBS SIGC_MACROS SOCKET_LIBS BUILD_NET_TRUE BUILD_NET_FALSE TIMER_LIBS BUILD_TIMER_TRUE BUILD_TIMER_FALSE GL_LIBS BUILD_GL_TRUE BUILD_GL_FALSE target target_cpu target_vendor target_os SDL_CONFIG SDL_CFLAGS SDL_LIBS BUILD_VIDEO_TRUE BUILD_VIDEO_FALSE BUILD_INPUT_TRUE BUILD_INPUT_FALSE SDLMIXER_LIBS BUILD_AUDIO_TRUE BUILD_AUDIO_FALSE PKG_CONFIG ac_pt_PKG_CONFIG SVGL_CFLAGS SVGL_LIBS BUILD_SVGL_TRUE BUILD_SVGL_FALSE TCC_LIBS BUILD_TCC_TRUE BUILD_TCC_FALSE BUILD_LTDL_TRUE BUILD_LTDL_FALSE MODULE_LDFLAGS LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1064,6 +1064,7 @@ Optional Features:
   --enable-audio          Build audio module [default=yes]
   --enable-svgl           Build svgl module [default=no]
   --enable-tcc            Build tcc module [default=no]
+  --enable-ltdl           Build ltdl module [default=no]
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -4250,7 +4251,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4253 "configure"' > conftest.$ac_ext
+  echo '#line 4254 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -5596,7 +5597,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:5599:" \
+echo "$as_me:5600:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -6628,11 +6629,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6631: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6632: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6635: \$? = $ac_status" >&5
+   echo "$as_me:6636: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -6861,11 +6862,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6864: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6865: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6868: \$? = $ac_status" >&5
+   echo "$as_me:6869: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -6921,11 +6922,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6924: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6925: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:6928: \$? = $ac_status" >&5
+   echo "$as_me:6929: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -9109,7 +9110,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9112 "configure"
+#line 9113 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -9207,7 +9208,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9210 "configure"
+#line 9211 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11384,11 +11385,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11387: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11388: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:11391: \$? = $ac_status" >&5
+   echo "$as_me:11392: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -11444,11 +11445,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11447: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11448: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:11451: \$? = $ac_status" >&5
+   echo "$as_me:11452: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -12813,7 +12814,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12816 "configure"
+#line 12817 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12911,7 +12912,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12914 "configure"
+#line 12915 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13738,11 +13739,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13741: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13742: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:13745: \$? = $ac_status" >&5
+   echo "$as_me:13746: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -13798,11 +13799,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13801: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13802: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13805: \$? = $ac_status" >&5
+   echo "$as_me:13806: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -15843,11 +15844,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15846: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15847: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15850: \$? = $ac_status" >&5
+   echo "$as_me:15851: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -16076,11 +16077,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16079: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16080: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16083: \$? = $ac_status" >&5
+   echo "$as_me:16084: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -16136,11 +16137,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16139: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16140: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:16143: \$? = $ac_status" >&5
+   echo "$as_me:16144: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -18324,7 +18325,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 18327 "configure"
+#line 18328 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -18422,7 +18423,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 18425 "configure"
+#line 18426 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -21996,11 +21997,29 @@ else
 fi
 
 
+# Check whether --enable-ltdl or --disable-ltdl was given.
+if test "${enable_ltdl+set}" = set; then
+  enableval="$enable_ltdl"
+
+else
+  enable_ltdl=no
+fi;
+
+
+if test x$enable_ltdl = xyes; then
+  BUILD_LTDL_TRUE=
+  BUILD_LTDL_FALSE='#'
+else
+  BUILD_LTDL_TRUE='#'
+  BUILD_LTDL_FALSE=
+fi
+
+
 LDFLAGS="$LDFLAGS -thread-safe -pthread"
 MODULE_LDFLAGS="-avoid-version -no-undefined -export-symbols \$(srcdir)/export.sym"
 
 
-                                                                                                                                                                                                                                                                    ac_config_files="$ac_config_files Makefile tests/Makefile debian/Makefile src/Makefile src/etc/Makefile src/examples/Makefile src/modules/Makefile src/modules/example/Makefile src/modules/zlib/Makefile src/modules/monitorable/Makefile src/modules/stream/Makefile src/modules/file/Makefile src/modules/network/Makefile src/modules/bytearray/Makefile src/modules/egachine/Makefile src/modules/timer/Makefile src/modules/gl/Makefile src/modules/video/Makefile src/modules/video/boost/Makefile src/modules/input/Makefile src/modules/audio/Makefile src/modules/svgl/Makefile src/modules/util/Makefile src/modules/jsolait/Makefile src/modules/jsmisc/Makefile src/modules/tcc/Makefile"
+                                                                                                                                                                                                                                                                              ac_config_files="$ac_config_files Makefile tests/Makefile debian/Makefile src/Makefile src/etc/Makefile src/examples/Makefile src/modules/Makefile src/modules/example/Makefile src/modules/zlib/Makefile src/modules/monitorable/Makefile src/modules/stream/Makefile src/modules/file/Makefile src/modules/network/Makefile src/modules/bytearray/Makefile src/modules/egachine/Makefile src/modules/timer/Makefile src/modules/gl/Makefile src/modules/video/Makefile src/modules/video/boost/Makefile src/modules/input/Makefile src/modules/audio/Makefile src/modules/svgl/Makefile src/modules/util/Makefile src/modules/jsolait/Makefile src/modules/jsmisc/Makefile src/modules/tcc/Makefile src/modules/ltdl/Makefile"
 
 
 cat >confcache <<\_ACEOF
@@ -22220,6 +22239,13 @@ if test -z "${BUILD_TCC_TRUE}" && test -z "${BUILD_TCC_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"BUILD_TCC\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"BUILD_TCC\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${BUILD_LTDL_TRUE}" && test -z "${BUILD_LTDL_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"BUILD_LTDL\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"BUILD_LTDL\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -22688,6 +22714,7 @@ do
   "src/modules/jsolait/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/modules/jsolait/Makefile" ;;
   "src/modules/jsmisc/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/modules/jsmisc/Makefile" ;;
   "src/modules/tcc/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/modules/tcc/Makefile" ;;
+  "src/modules/ltdl/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/modules/ltdl/Makefile" ;;
   "depfiles" ) CONFIG_COMMANDS="$CONFIG_COMMANDS depfiles" ;;
   *) { { echo "$as_me:$LINENO: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
@@ -22891,6 +22918,8 @@ s,@BUILD_SVGL_FALSE@,$BUILD_SVGL_FALSE,;t t
 s,@TCC_LIBS@,$TCC_LIBS,;t t
 s,@BUILD_TCC_TRUE@,$BUILD_TCC_TRUE,;t t
 s,@BUILD_TCC_FALSE@,$BUILD_TCC_FALSE,;t t
+s,@BUILD_LTDL_TRUE@,$BUILD_LTDL_TRUE,;t t
+s,@BUILD_LTDL_FALSE@,$BUILD_LTDL_FALSE,;t t
 s,@MODULE_LDFLAGS@,$MODULE_LDFLAGS,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
