Added image module.

diff --git a/egachine/configure b/egachine/configure
--- a/egachine/configure
+++ b/egachine/configure
@@ -466,7 +466,7 @@ ac_includes_default="\
 #endif"
 
 ac_subdirs_all="$ac_subdirs_all libltdl"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CC CFLAGS ac_ct_CC CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE LTDLINCL LIBLTDL build build_cpu build_vendor build_os host host_cpu host_vendor host_os EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB DLLTOOL ac_ct_DLLTOOL AS ac_ct_AS OBJDUMP ac_ct_OBJDUMP CPP CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL subdirs EJS_CFLAGS ZLIB_LIBS BUILD_ZLIB_TRUE BUILD_ZLIB_FALSE BUILD_STREAM_TRUE BUILD_STREAM_FALSE BUILD_FILE_TRUE BUILD_FILE_FALSE SIGC_CONFIG SIGC_CFLAGS SIGC_LIBS SIGC_MACROS SOCKET_LIBS BUILD_NET_TRUE BUILD_NET_FALSE TIMER_LIBS BUILD_TIMER_TRUE BUILD_TIMER_FALSE GL_LIBS BUILD_GL_TRUE BUILD_GL_FALSE target target_cpu target_vendor target_os SDL_CONFIG SDL_CFLAGS SDL_LIBS BUILD_VIDEO_TRUE BUILD_VIDEO_FALSE BUILD_INPUT_TRUE BUILD_INPUT_FALSE SDLMIXER_LIBS BUILD_AUDIO_TRUE BUILD_AUDIO_FALSE PKG_CONFIG ac_pt_PKG_CONFIG SVGL_CFLAGS SVGL_LIBS BUILD_SVGL_TRUE BUILD_SVGL_FALSE TCC_LIBS BUILD_TCC_TRUE BUILD_TCC_FALSE BUILD_LTDL_TRUE BUILD_LTDL_FALSE MODULE_LDFLAGS LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CC CFLAGS ac_ct_CC CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE LTDLINCL LIBLTDL build build_cpu build_vendor build_os host host_cpu host_vendor host_os EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB DLLTOOL ac_ct_DLLTOOL AS ac_ct_AS OBJDUMP ac_ct_OBJDUMP CPP CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL subdirs EJS_CFLAGS ZLIB_LIBS BUILD_ZLIB_TRUE BUILD_ZLIB_FALSE BUILD_STREAM_TRUE BUILD_STREAM_FALSE BUILD_FILE_TRUE BUILD_FILE_FALSE SIGC_CONFIG SIGC_CFLAGS SIGC_LIBS SIGC_MACROS SOCKET_LIBS BUILD_NET_TRUE BUILD_NET_FALSE TIMER_LIBS BUILD_TIMER_TRUE BUILD_TIMER_FALSE GL_LIBS BUILD_GL_TRUE BUILD_GL_FALSE target target_cpu target_vendor target_os SDL_CONFIG SDL_CFLAGS SDL_LIBS BUILD_VIDEO_TRUE BUILD_VIDEO_FALSE BUILD_IMAGE_TRUE BUILD_IMAGE_FALSE BUILD_INPUT_TRUE BUILD_INPUT_FALSE SDLMIXER_LIBS BUILD_AUDIO_TRUE BUILD_AUDIO_FALSE PKG_CONFIG ac_pt_PKG_CONFIG SVGL_CFLAGS SVGL_LIBS BUILD_SVGL_TRUE BUILD_SVGL_FALSE TCC_LIBS BUILD_TCC_TRUE BUILD_TCC_FALSE BUILD_LTDL_TRUE BUILD_LTDL_FALSE MODULE_LDFLAGS LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1060,6 +1060,7 @@ Optional Features:
   --enable-gl             Build gl (opengl) module [default=yes]
   --enable-video          Build video module [default=yes]
   --disable-sdltest       Do not try to compile and run a test SDL program
+  --enable-image          Build image module [default=yes]
   --enable-input          Build input module [default=yes]
   --enable-audio          Build audio module [default=yes]
   --enable-svgl           Build svgl module [default=no]
@@ -4251,7 +4252,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4254 "configure"' > conftest.$ac_ext
+  echo '#line 4255 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -5597,7 +5598,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:5600:" \
+echo "$as_me:5601:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -6629,11 +6630,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6632: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6633: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6636: \$? = $ac_status" >&5
+   echo "$as_me:6637: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -6862,11 +6863,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6865: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6866: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6869: \$? = $ac_status" >&5
+   echo "$as_me:6870: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -6922,11 +6923,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6925: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6926: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:6929: \$? = $ac_status" >&5
+   echo "$as_me:6930: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -9110,7 +9111,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9113 "configure"
+#line 9114 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -9208,7 +9209,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9211 "configure"
+#line 9212 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11385,11 +11386,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11388: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11389: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:11392: \$? = $ac_status" >&5
+   echo "$as_me:11393: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -11445,11 +11446,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11448: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11449: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:11452: \$? = $ac_status" >&5
+   echo "$as_me:11453: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -12814,7 +12815,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12817 "configure"
+#line 12818 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12912,7 +12913,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12915 "configure"
+#line 12916 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13739,11 +13740,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13742: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13743: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:13746: \$? = $ac_status" >&5
+   echo "$as_me:13747: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -13799,11 +13800,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13802: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13803: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13806: \$? = $ac_status" >&5
+   echo "$as_me:13807: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -15844,11 +15845,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15847: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15848: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15851: \$? = $ac_status" >&5
+   echo "$as_me:15852: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -16077,11 +16078,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16080: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16081: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16084: \$? = $ac_status" >&5
+   echo "$as_me:16085: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -16137,11 +16138,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16140: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16141: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:16144: \$? = $ac_status" >&5
+   echo "$as_me:16145: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -18325,7 +18326,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 18328 "configure"
+#line 18329 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -18423,7 +18424,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 18426 "configure"
+#line 18427 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -21331,6 +21332,31 @@ else
 fi
 
 
+# Check whether --enable-image or --disable-image was given.
+if test "${enable_image+set}" = set; then
+  enableval="$enable_image"
+
+else
+  enable_image=yes
+fi;
+if test x$enable_image = xyes; then
+		if test x$enable_video != xyes; then
+		{ { echo "$as_me:$LINENO: error: image module requires video module" >&5
+echo "$as_me: error: image module requires video module" >&2;}
+   { (exit 1); exit 1; }; }
+	fi
+			fi
+
+
+if test x$enable_image = xyes; then
+  BUILD_IMAGE_TRUE=
+  BUILD_IMAGE_FALSE='#'
+else
+  BUILD_IMAGE_TRUE='#'
+  BUILD_IMAGE_FALSE=
+fi
+
+
 # Check whether --enable-input or --disable-input was given.
 if test "${enable_input+set}" = set; then
   enableval="$enable_input"
@@ -22019,7 +22045,7 @@ LDFLAGS="$LDFLAGS -thread-safe -pthread"
 MODULE_LDFLAGS="-avoid-version -no-undefined -export-symbols \$(srcdir)/export.sym"
 
 
-                                                                                                                                                                                                                                                                              ac_config_files="$ac_config_files Makefile tests/Makefile debian/Makefile src/Makefile src/etc/Makefile src/examples/Makefile src/modules/Makefile src/modules/example/Makefile src/modules/zlib/Makefile src/modules/monitorable/Makefile src/modules/stream/Makefile src/modules/file/Makefile src/modules/network/Makefile src/modules/bytearray/Makefile src/modules/egachine/Makefile src/modules/timer/Makefile src/modules/gl/Makefile src/modules/video/Makefile src/modules/video/boost/Makefile src/modules/input/Makefile src/modules/audio/Makefile src/modules/svgl/Makefile src/modules/util/Makefile src/modules/jsolait/Makefile src/modules/jsmisc/Makefile src/modules/tcc/Makefile src/modules/ltdl/Makefile"
+                                                                                                                                                                                                                                                                                        ac_config_files="$ac_config_files Makefile tests/Makefile debian/Makefile src/Makefile src/etc/Makefile src/examples/Makefile src/modules/Makefile src/modules/example/Makefile src/modules/zlib/Makefile src/modules/monitorable/Makefile src/modules/stream/Makefile src/modules/file/Makefile src/modules/network/Makefile src/modules/bytearray/Makefile src/modules/egachine/Makefile src/modules/timer/Makefile src/modules/gl/Makefile src/modules/video/Makefile src/modules/video/boost/Makefile src/modules/image/Makefile src/modules/input/Makefile src/modules/audio/Makefile src/modules/svgl/Makefile src/modules/util/Makefile src/modules/jsolait/Makefile src/modules/jsmisc/Makefile src/modules/tcc/Makefile src/modules/ltdl/Makefile"
 
 
 cat >confcache <<\_ACEOF
@@ -22211,6 +22237,13 @@ if test -z "${BUILD_VIDEO_TRUE}" && test -z "${BUILD_VIDEO_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"BUILD_VIDEO\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"BUILD_VIDEO\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${BUILD_IMAGE_TRUE}" && test -z "${BUILD_IMAGE_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"BUILD_IMAGE\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"BUILD_IMAGE\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -22707,6 +22740,7 @@ do
   "src/modules/gl/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/modules/gl/Makefile" ;;
   "src/modules/video/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/modules/video/Makefile" ;;
   "src/modules/video/boost/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/modules/video/boost/Makefile" ;;
+  "src/modules/image/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/modules/image/Makefile" ;;
   "src/modules/input/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/modules/input/Makefile" ;;
   "src/modules/audio/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/modules/audio/Makefile" ;;
   "src/modules/svgl/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/modules/svgl/Makefile" ;;
@@ -22904,6 +22938,8 @@ s,@SDL_CFLAGS@,$SDL_CFLAGS,;t t
 s,@SDL_LIBS@,$SDL_LIBS,;t t
 s,@BUILD_VIDEO_TRUE@,$BUILD_VIDEO_TRUE,;t t
 s,@BUILD_VIDEO_FALSE@,$BUILD_VIDEO_FALSE,;t t
+s,@BUILD_IMAGE_TRUE@,$BUILD_IMAGE_TRUE,;t t
+s,@BUILD_IMAGE_FALSE@,$BUILD_IMAGE_FALSE,;t t
 s,@BUILD_INPUT_TRUE@,$BUILD_INPUT_TRUE,;t t
 s,@BUILD_INPUT_FALSE@,$BUILD_INPUT_FALSE,;t t
 s,@SDLMIXER_LIBS@,$SDLMIXER_LIBS,;t t
